### PR TITLE
With mod.json

### PR DESCRIPTION
**Pull request by donZappo**
Sorry, forgot to add the mod.json. Here's the fully working code with the mod.json updated to our current values.

### CODE REVIEW

**Comment by janxious** [comment]
What is the intent of the PR? There are no README changes, and there are two `mod.json`s. Maybe add a bit more description to the PR, or tell me to buzz off because it's not my biz :D

**Comment by donZappo** [comment]
Oh, did I send that to you? Sorry! I am learning get and today I was
learning pull requests. I meant to put the request to gnivler's fork
(branch?) but I guess it went to you!

**Comment by janxious** [comment]
It's on gnivler's fork, but I have repo access, so I saw the PR come in.

**Comment by gnivler** [comment]
Yeah sorry dZ the PR isn't gonna work, it's got our old stuff in it.  master is updated to your last dev branch.  I'll add you to this project so you can work on it directly

**Pull request closed without merging**
